### ISSUE TITLE
CairoMakie: line data exists outside the plotting region

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#2385]
This is more an issue with Cairo than CairoMakie per se, but can be a good perf optimization when looking at zoomed-in plots.  Consider the following screenshot (from Figma):
<img width="1728" alt="Screen Shot 2022-10-30 at 11 29 29 AM" src="https://user-images.githubusercontent.com/32143268/198865356-e4448fdd-b42a-4010-81f7-4d9e5d1a77ce.png">

Note that the line extends outside the region of the plot even though it has been cropped there by Cairo.  This is also the case in PDF, and can lead to large filesizes for seemingly no reason.

One way to optimize this would be to add an optional flag, wherein `draw_single` or `draw_multiple` can just not plot any lines which do not intersect the clipping rectangle of the Scene.  Since this might take some extra time (it does have to check every line segment) it could be turned off for interactive/fast/PNG use and on for PDF/SVG.

**Comment by ffreyer** [comment]
May have been fixed by #3958

**Comment by ffreyer** [comment]
I did not test this

**Comment by SimonDanisch** [comment]
Yeah, there is no MWE here and it's pretty plausible that it got fixed, so I think it's better to close and re-open once someone tests this and it isnt fixed ;)
