### ISSUE TITLE
High resolution figures get cropped when saving to PNG

### ISSUE THREAD

**Issue by myersm0** [MakieOrg/Makie.jl#2526]
Some months back, I was having an issue in GLMakie with needing to produce some high resolution figures exceeding my monitor's resolution, but when saving the output as png it would always result in figures getting cropped roughly to my screen resolution. Someone else posted an issue ([https://github.com/MakieOrg/Makie.jl/issues/440]) and the fix that was provided there worked for me at the time.

However, upon upgrading to Julia 1.8.3 and re-installing Makie (v0.19.0), I'm having the same problem again. Here's an example. The resulting png figure ends up being 2560 x 1385. My monitor resolution is 2560 x 1440. OS is Linux (Ubuntu 22.04).
```

using GLMakie
w = 5000
h = 3000
fig = Figure(resolution = (w, h))
ax = Axis(fig[1, 1], width = w, height = h)
x = range(0, stop = 2pi, length = 40)
y = sin.(x)
lines!(ax, x, y)
save("test.png", fig)
```

**Comment by myersm0** [comment]
I've been able to replicate this problem on Windows 10 as well. It's strange that I didn't have this problem prior to the OS and Julia upgrades that I did last month (Ubuntu 20 -> Ubuntu 22, Julia 1.7.1 -> Julia 1.8.3), but now it affects me seemingly regardless of OS, Julia version, or Makie version, as I've tried out lots of different combinations.

I've made some progress and can now get a GLMakie figure to preserve my specified resolution, via setting the scene's px_area, and then using the Cairo backend to save as png. This produces an image of the required resolution, but unfortunately the axis content is not centered on the image; it ends up pushed to the bottom left corner, with part of the sine curve getting cut off.

I've done some debugging with the GLMakie code and I can see that if you execute the below steps, the figure starts out at the required resolution (fig = Figure(resolution = (w, h)) but then it gets resized along with the framebuffer in render.jl. I can force it back to the desired size by setting px_area and am then able to preserve that resolution, but at the cost of an apparent miscommunication between the axis and its parent figure.

If anyone has ideas, please let me know. I'm a little limited in my ability to decipher the code, not knowing GLFW or OpenGL, but I'm committed to fixing this so I may have to do some learning.

```
using GLMakie
w = 5000
h = 3000
fig = Figure(resolution = (w, h))
fig.scene.px_area = Observable(HyperRectangle{2, Int64}([0, 0], [w, h]))
ax = Axis(fig[1, 1], width = w, height = h)
x = range(0, 2pi, length = 40)
y = sin.(x)
lines!(ax, x, y)
using CairoMakie
CairoMakie.save("test.png", fig)
```

**Comment by myersm0** [comment]
Update: I was able to turn the above into a fully functioning workaround by removing the [1, 1] indexing from fig in the Axis() call, and then specifying a bounding box instead of just a height and width:

```
using GLMakie
using GeometryBasics
w = 5000
h = 3000
fig = Figure(resolution = (w, h))
fig.scene.px_area = Observable(HyperRectangle{2, Int64}([0, 0], [w, h]))
ax = Axis(fig, bbox = BBox(0, w, 0, h)
x = range(0, 2pi, length = 40)
y = sin.(x)
lines!(ax, x, y)
using CairoMakie
CairoMakie.save("test.png", fig)
```

What remains unclear, though, is how I would do something similar using a GridLayout instead of an axis. For example, plotting a mesh with mesh!(fig.layout, ...) results in everything getting pushed to the lower lefthand corner. The same happens if I make a GridLayout object and attach it to fig.

**Comment by SimonDanisch** [comment]
I think this is fixed... If not please re-open!

**Comment by champLisse** [comment]
I still have this issue on Windows 11, GLMakie 0.11, Makie 0.22

In fact I also have the inverse problem, when plotting a figure in tiny sizes Windows does not want to display such tiny windows and i obtain pictures with extra whitespace.

The cropping/extra whitespace in the pgn obtained from `save` seems to exactly correspond to the size of the window that I obtain when using `display`.

My workaround: use a size that Windows thinks is reasonable and scale the image using a large value for `px_per_unit`.

**Comment by asinghvi17** [comment]
Does that also happen with WGLMakie, or is it restricted to GLMakie?

**Comment by champLisse** [comment]
From my testing WGLMakie seems works as expected, so it is restricted to GLMakie.

**Comment by asinghvi17** [comment]
Is there any lower bound, above which the sizing seems to be correct with no whitespace?  You could try the https://docs.makie.org/dev/tutorials/pixel-perfect-rendering#Pixel-Perfect-Rendering tutorial to obtain exact sizes and measurements of the whitespace.

**Comment by champLisse** [comment]
Display does affect the output, but in a strange way..
Here are two actual examples of output.
As far as I can tell the rectangles that appear without display are the same size as the ones without display. Only the whitespace is different.

```
using GLMakie

for s = [50, 100, 200, 500, 1000, 2000, 5000]
    begin
    fig = Figure(size = (s, s))
    Box(fig[1, 1], color = :red, width = s, height = s)
    save("figure_inside_begin_end" * string(s) * ".png", fig, px_per_unit = 1)
    end
end

```

![Image](https://github.com/user-attachments/assets/059c8466-55c8-4b74-815e-ce200441bc05)
![Image](https://github.com/user-attachments/assets/c184edfc-a361-4fb6-9e0f-784c78175ad3)
![Image](https://github.com/user-attachments/assets/f75382b0-9cc4-4058-a6fd-964f9befe794)
![Image](https://github.com/user-attachments/assets/b92ed19b-11c7-4b16-b2d7-e1976d8a7004)
![Image](https://github.com/user-attachments/assets/9a91e341-9a08-4ff1-9a33-aa76f94b4c8f)
![Image](https://github.com/user-attachments/assets/afb3bac8-2532-4b95-96c2-442e49014c0f)
![Image](https://github.com/user-attachments/assets/9e72596e-e12f-4d3b-8aba-b95e9e5ed859)

```
using GLMakie

for s = [50, 100, 200, 500, 1000, 2000, 5000]
    fig = Figure(size = (s, s))
    Box(fig[1, 1], color = :red, width = s, height = s)
    display(fig)
    save("figure_after_display" * string(s) * ".png", fig, px_per_unit = 1)
end
```

![Image](https://github.com/user-attachments/assets/8f596f5e-c8c3-4c1e-981e-2ae7769c10e2)
![Image](https://github.com/user-attachments/assets/fd798790-677c-4049-9cf0-4ab50f279f37)
![Image](https://github.com/user-attachments/assets/f7a5e845-3e00-470a-95b3-394fc87228ab)
![Image](https://github.com/user-attachments/assets/6bd7c074-0184-4d27-8ee2-369c524f8fb9)
![Image](https://github.com/user-attachments/assets/576712a1-a93f-451d-8018-b07d70c2e611)
![Image](https://github.com/user-attachments/assets/cedbc774-144c-4090-ba27-aaabcd3efc9d)
![Image](https://github.com/user-attachments/assets/4dc37fc9-95ff-4e9e-85f3-71472bb31e04)
