### ISSUE TITLE
[WGLMakie]: image and heatmap  `Error: handle_connection handler error`

### ISSUE THREAD

**Issue by f3fora** [MakieOrg/Makie.jl#2930]
I was using WGLMakie in Pluto.
Everything works fine except for `heatmap` and `image` which are not displayed.
I discover that these functions actually works if are used e.g. in a simple script as the following one, even if on load or reload of the webpage an error is printed.

```julia
using JSServe
using WGLMakie
using FileIO

# Raise error on load/reload
function imagex()
    server = Server("127.0.0.1", 1234)
    route!(server, "/" => App() do
        img = load(assetpath("icons/icon-64.png"))
        image(img, axis=(aspect=DataAspect(),))
    end)
end

# Raise error on load/reload
function heatmapx()
    server = Server("127.0.0.1", 2345)
    route!(server, "/" => App() do
        heatmap(reshape(1:64*64, 64, 64))
    end)
end

# Works
function heatmapy()
    server = Server("127.0.0.1", 3456)
    route!(server, "/" => App() do
        heatmap(1:64, 1:64, 1:64)
    end)
end
```

```
┌ Error: handle_connection handler error
│   exception =
│    IOError: write: broken pipe (EPIPE)
│    Stacktrace:
│      [1] uv_write(s::Sockets.TCPSocket, p::Ptr{UInt8}, n::UInt64)
│        @ Base ./stream.jl:1064
│      [2] unsafe_write(s::Sockets.TCPSocket, p::Ptr{UInt8}, n::UInt64)
│        @ Base ./stream.jl:1118
│      [3] unsafe_write
│        @ ~/.julia/packages/HTTP/qGpdS/src/Connections.jl:122 [inlined]
│      [4] write
│        @ ./strings/io.jl:244 [inlined]
│      [5] write
│        @ ./io.jl:674 [inlined]
│      [6] unsafe_write(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}}, p::Ptr{UInt8}, n::UInt64)
│        @ HTTP.Streams ~/.julia/packages/HTTP/qGpdS/src/Streams.jl:95
│      [7] write
│        @ ./strings/io.jl:244 [inlined]
│      [8] write(io::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}}, s::Base.CodeUnits{UInt8, String})
│        @ Base ./strings/basic.jl:758
│      [9] (::HTTP.Handlers.var"#1#2"{JSServe.HTTPServer.var"#12#14"{JSServe.HTTPServer.Server}})(stream::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Co
nnections.Connection{Sockets.TCPSocket}})
│        @ HTTP.Handlers ~/.julia/packages/HTTP/qGpdS/src/Handlers.jl:61
│     [10] stream_handler(application::JSServe.HTTPServer.Server, stream::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCP
Socket}})
│        @ JSServe.HTTPServer ~/.julia/packages/JSServe/zGefk/src/HTTPServer/implementation.jl:150
│     [11] #invokelatest#2
│        @ ./essentials.jl:729 [inlined]
│     [12] invokelatest
│        @ ./essentials.jl:726 [inlined]
│     [13] (::JSServe.HTTPServer.var"#21#23"{JSServe.HTTPServer.Server})(stream::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sock
ets.TCPSocket}})
│        @ JSServe.HTTPServer ~/.julia/packages/JSServe/zGefk/src/HTTPServer/implementation.jl:260
│     [14] #invokelatest#2
│        @ ./essentials.jl:729 [inlined]
│     [15] invokelatest
│        @ ./essentials.jl:726 [inlined]
│     [16] handle_connection(f::Function, c::HTTP.Connections.Connection{Sockets.TCPSocket}, listener::HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, re
adtimeout::Int64, access_log::Nothing)
│        @ HTTP.Servers ~/.julia/packages/HTTP/qGpdS/src/Servers.jl:447
│     [17] (::HTTP.Servers.var"#16#17"{JSServe.HTTPServer.var"#21#23"{JSServe.HTTPServer.Server}, HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, Set{HTT
P.Connections.Connection}, Int64, Nothing, Base.Semaphore, HTTP.Connections.Connection{Sockets.TCPSocket}})()
│        @ HTTP.Servers ./task.jl:484
└ @ HTTP.Servers ~/.julia/packages/HTTP/qGpdS/src/Servers.jl:461
```

WGLMakie version = "0.8.8"
Julia version = "1.8.5"

**Comment by SimonDanisch** [comment]
I can't reproduce this in neither firefox nor chrome.
Can you give some more details about your versions and how to reproduce this?

**Comment by f3fora** [comment]
It seems fixed with julia 1.9.0

**Comment by SimonDanisch** [comment]
Unlikely ... I made some small patch releases recently in JSServe, which may have helped (although I'm still not 100% sure how this may happen)
So, maybe that fixed it and you updated JSServe when switching Julia versions?
