### ISSUE TITLE
Rotated LaTeXString labels with fractions displayed incorrectly.

### ISSUE THREAD

**Issue by Whyborn** [MakieOrg/Makie.jl#3130]
Rotated axis labels (tested with regular `Axis` labels and `Colorbar` labels) that contain LaTeX fractions are incorrectly displayed. The vinculum is misplaced by varying amounts. Occurs when `labelrotation` is defined, even if the rotation is 0.

**Comment by ffreyer** [comment]
Fixed

**Comment by TomRottier** [comment]
I am still getting this issue on CairoMakie v0.13.4 and GLMakie v0.11.5:

```julia
f = Figure()
ax = Axis(f[1,1],  ylabel=L"\frac{\sin x}{2x}", ylabelrotation=0)
```

![Image](https://github.com/user-attachments/assets/d88750a8-46a4-4e6b-85ed-f1f9d08c4d90)
