### ISSUE TITLE
Standalone Latex backend support

### ISSUE THREAD

**Issue by albertomercurio** [MakieOrg/Makie.jl#3634]
Hello,

I was wondering on a possible implementation of a standalone Latex backend. Matplotlib already has this feature, with the possibility to even define a preamble

```python
matplotlib.rc("text", usetex = true)
matplotlib.rc("text.latex", preamble = raw"\usepackage{amsmath} \usepackage{physics}")
```

So that I'm able to use the `physics` package in my figures.

I know that Makie.jl uses MathTeXEngine.jl for the Latex, and I think it is a great solution for simple implementations. However,  I think that it might be a limit in several circumstances. For instance, as I already mentioned, when using external packages, or when a different font is needed.

**Comment by ffreyer** [comment]
Maybe solved by https://github.com/JuliaPlots/MakieTeX.jl?

**Comment by asinghvi17** [comment]
Yep, that's the idea!

**Comment by albertomercurio** [comment]
Ok, thanks. It seems to still not be ready for a general preamble with a general package, right? But it is on the way to do it. So, great.

**Comment by asinghvi17** [comment]
You can create a TeXDocument which is just a regular latex document (though not multi file).  So it can render arbitrary latex including packages.  Just put the entire document as a String into the TeXDocument constructor.

**Comment by albertomercurio** [comment]
I tried MakieTeX, and I found it very useful. However, I still think that the support for a standalone latex directly in Makie would be nice.

For example, if I want to write the label of the x-axis with a custom latex preamble, I have to create the `LTeX` object and then place it in the correct position for the x-axis label. The same would happen for Legend labels or Colorbar legends.
